import PDFDocument from "pdfkit";

const GREEN = "#1b4332";
const CREAM = "#f4f1e8";
const TEXT = "#1c2b22";
const MUTED = "#5c6b62";
const GOLD = "#8a7f5f";
const RED = "#a4341f";
const ROW_LINE = "#e4ded0";

export function generateSummaryPdf({ filters, summary, sessionCount, teacherName }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 40, bufferPages: true });

    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageLeft = doc.page.margins.left;
    const pageWidth = doc.page.width - pageLeft - doc.page.margins.right;

    // ---------- Header ----------
    doc.fillColor(GREEN).font("Helvetica-Bold").fontSize(20).text("Attendance Summary Report");
    doc.moveDown(0.15);
    doc.font("Helvetica").fontSize(9).fillColor(MUTED);
    doc.text(`Generated by ${teacherName || "—"}`, { continued: true });
    doc.text(`   ·   ${new Date().toLocaleString()}`);

    // ---------- Meta box ----------
    const metaRows = [
      ["Department", filters.department || "—"],
      ["Batch", String(filters.batch ?? "—")],
      ["Section", filters.section || "—"],
      ["Course", filters.courseName || "—"],
      ["Sessions Counted", String(sessionCount ?? 0)],
      ["From", filters.from || "—"],
      ["To", filters.to || "—"],
    ];

    let boxTop = doc.y + 14;
    const colW = pageWidth / 4;
    const rowH = 30;
    const boxH = Math.ceil(metaRows.length / 4) * rowH + 12;

    doc.save();
    doc.roundedRect(pageLeft, boxTop, pageWidth, boxH, 6).fillOpacity(1).fill(CREAM);
    doc.restore();

    metaRows.forEach(([label, value], i) => {
      const col = i % 4;
      const row = Math.floor(i / 4);
      const x = pageLeft + 10 + col * colW;
      const y = boxTop + 8 + row * rowH;
      doc.font("Helvetica").fontSize(7).fillColor(GOLD).text(label.toUpperCase(), x, y, {
        characterSpacing: 0.5,
        lineBreak: false,
      });
      doc.font("Helvetica-Bold").fontSize(10).fillColor(TEXT).text(value, x, y + 11, {
        lineBreak: false,
        ellipsis: true,
        width: colW - 16,
      });
    });

    doc.y = boxTop + boxH + 18;

    // ---------- Table ----------
    const cols = [
      { key: "#", label: "#", w: 0.06, align: "left" },
      { key: "studentId", label: "Student ID", w: 0.17, align: "left" },
      { key: "name", label: "Name", w: 0.34, align: "left" },
      { key: "present", label: "Present", w: 0.105, align: "right" },
      { key: "absent", label: "Absent", w: 0.105, align: "right" },
      { key: "total", label: "Total", w: 0.105, align: "right" },
      { key: "pct", label: "%", w: 0.115, align: "right" },
    ].map((c) => ({ ...c, w: c.w * pageWidth }));

    const drawTableHeader = () => {
      const y = doc.y;
      doc.save();
      doc.rect(pageLeft, y, pageWidth, 22).fill(GREEN);
      doc.restore();
      let x = pageLeft;
      for (const c of cols) {
        doc.font("Helvetica-Bold").fontSize(8).fillColor(CREAM)
          .text(c.label.toUpperCase(), x + (c.align === "right" ? 0 : 8), y + 7, {
            width: c.w - (c.align === "right" ? 8 : 8),
            align: c.align,
            lineBreak: false,
          });
        x += c.w;
      }
      doc.y = y + 22;
    };

    drawTableHeader();

    const drawRow = (row, i) => {
      const cells = {
        "#": String(i + 1),
        studentId: row.student.studentId,
        name: row.student.name,
        present: String(row.present),
        absent: String(row.absent),
        total: String(row.total),
        pct: `${row.percentage}%`,
      };
      const low = row.percentage < 75;

      // measure row height (name may wrap)
      const nameCol = cols.find((c) => c.key === "name");
      const nameH = doc.font("Helvetica").fontSize(9).heightOfString(cells.name, {
        width: nameCol.w - 16,
      });
      const rowH = Math.max(20, nameH + 10);

      // page break if needed
      if (doc.y + rowH > doc.page.height - doc.page.margins.bottom - 30) {
        doc.addPage();
        drawTableHeader();
      }

      if (i % 2 === 0) {
        doc.save();
        doc.rect(pageLeft, doc.y, pageWidth, rowH).fill("#faf7ee");
        doc.restore();
      }

      const rowY = doc.y;
      let x = pageLeft;
      for (const c of cols) {
        const isPct = c.key === "pct";
        doc
          .font(isPct && low ? "Helvetica-Bold" : "Helvetica")
          .fontSize(9)
          .fillColor(isPct && low ? RED : TEXT)
          .text(cells[c.key], x + (c.align === "right" ? 0 : 8), rowY + 5, {
            width: c.w - 16,
            align: c.align,
            lineBreak: false,
          });
        x += c.w;
      }

      doc.moveTo(pageLeft, rowY + rowH)
        .lineTo(pageLeft + pageWidth, rowY + rowH)
        .lineWidth(0.5)
        .strokeColor(ROW_LINE)
        .stroke();

      doc.y = rowY + rowH;
    };

    summary.forEach((row, i) => drawRow(row, i));

    if (summary.length === 0) {
      doc.font("Helvetica").fontSize(9).fillColor(GOLD)
        .text("No attendance data for the selected filters", pageLeft, doc.y + 10, {
          width: pageWidth,
          align: "center",
        });
      doc.y += 30;
    }

    // ---------- Footer on every page ----------
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      const y = doc.page.height - doc.page.margins.bottom - 14;
      doc.font("Helvetica").fontSize(7.5).fillColor(GOLD);
      doc.text("Student Attendance Management System", pageLeft, y, {
        width: pageWidth / 2,
        lineBreak: false,
      });
      doc.text("Rows below 75% attendance are flagged", pageLeft + pageWidth / 2, y, {
        width: pageWidth / 2,
        align: "right",
        lineBreak: false,
      });
    }

    doc.end();
  });
}
